def report_agent(brand_name: str, trends: list, brand_analysis: dict, 
                  ethics: dict, psychology: dict, influencers: dict,
                  synthesis: dict, critic: dict, content: dict) -> str:
    """
    Report Agent
    
    Job: Compile all 7 agents' outputs into one polished markdown report.
    This is a FORMATTING agent, not a reasoning agent — it doesn't call 
    Gemini. All the thinking already happened upstream.
    
    Input: outputs from every agent in the pipeline
    Output: a single markdown string ready to display or export as PDF
    """
    
    print(f"[Report] Compiling final report for {brand_name}...")
    
    # We build the report as one long string, section by section.
    # Using an f-string with triple quotes lets us write multi-line 
    # markdown naturally.
    
    report = f"""# ModaMind Brand Intelligence Report
## {brand_name}

*Generated by a 10-agent AI pipeline | Quality Score: {critic.get('score', 'N/A')}/10*

---

## 📋 Executive Summary

{synthesis.get('executive_summary', 'N/A')}

**🎯 Top Opportunity:** {synthesis.get('top_opportunity', 'N/A')}

**🔗 Cross-Agent Insight:** {synthesis.get('cross_agent_insight', 'N/A')}

**⚠️ Risk Flag:** {synthesis.get('risk_flag', 'N/A')}

---

## 📈 Trend Intelligence

"""
    
    # Loop through the trends list and add each one as a bullet
    # This is why Trend Scout returns a LIST — so we can iterate over it
    for trend in trends:
        report += f"""**{trend.get('trend_name', 'Unknown')}** — Momentum: {trend.get('momentum_score', 'N/A')}/10
{trend.get('cultural_context', '')}
*Action: {trend.get('actionability', '')}*

"""
    
    report += f"""---

## 🏷️ Brand Positioning Analysis

**Current Positioning:** {brand_analysis.get('current_positioning', 'N/A')}

**Strengths:**
"""
    for strength in brand_analysis.get('strengths', []):
        report += f"- {strength}\n"
    
    report += "\n**Gaps:**\n"
    for gap in brand_analysis.get('gaps', []):
        report += f"- {gap}\n"
    
    report += f"""
**Opportunity Summary:** {brand_analysis.get('opportunity_summary', 'N/A')}

---

## 🧠 Consumer Psychology — Why It Works

**Why it worked:** {psychology.get('why_it_worked', 'N/A')}

**Primary Trigger:** {psychology.get('primary_trigger', 'N/A')}

**What Customers Actually Felt:** {psychology.get('what_customers_felt', 'N/A')}

**Sentiment Score:** {psychology.get('sentiment_score', 'N/A')}/10

**Key Lesson:** {psychology.get('key_lesson', 'N/A')}

---

## ♻️ Ethics & Sustainability Audit

**Credibility Score:** {ethics.get('credibility_score', 'N/A')}/10 ({ethics.get('credibility_label', 'N/A')})

**Recommendation:** {ethics.get('recommendation', 'N/A')}

---

## 🤝 Influencer Shortlist

"""
    
    for inf in influencers.get('shortlist', []):
        flag = "🇮🇳" if inf.get('region') == 'India' else "🌍"
        report += f"""{flag} **{inf.get('name', 'Unknown')}** ({inf.get('platform', 'N/A')}) — Fit Score: {inf.get('fit_score', 'N/A')}/10
{inf.get('why_they_fit', '')}
*Suggested format: {inf.get('collaboration_format', '')}*

"""
    
    report += f"""---

## ✍️ Campaign-Ready Content

### Instagram Captions
"""
    for cap in content.get('instagram_captions', []):
        report += f"""**[{cap.get('tone', '')}]**
{cap.get('caption', '')}
{cap.get('hashtags', '')}

"""
    
    report += f"""### Email Subject Line
{content.get('email_subject', 'N/A')}

### Ad Headlines
"""
    for headline in content.get('ad_headlines', []):
        report += f"- {headline}\n"
    
    report += f"""
### Brand Story
{content.get('brand_story', 'N/A')}

---

## ✅ Recommended Actions

"""
    for i, action in enumerate(synthesis.get('recommended_actions', []), 1):
        report += f"{i}. {action}\n"
    
    report += f"""
---

*Quality reviewed by Critic Agent — Score: {critic.get('score', 'N/A')}/10*
*Built with ModaMind — a 10-agent AI brand intelligence platform*
"""
    
    print(f"[Report] ✓ Report compiled ({len(report)} characters)")
    return report


if __name__ == "__main__":
    # Minimal sample test — just confirming the formatting logic works,
    # not testing real AI-generated content
    print("Testing Report Agent with minimal sample data...")
    print("=" * 50)
    
    sample_report = report_agent(
        brand_name="Nike",
        trends=[{"trend_name": "Gully-Tech", "momentum_score": 9, 
                 "cultural_context": "Street culture fusion", 
                 "actionability": "Launch capsule collection"}],
        brand_analysis={"current_positioning": "Premium sportswear", 
                        "strengths": ["Global brand power"], 
                        "gaps": ["Mid-market pricing"], 
                        "opportunity_summary": "Bridge premium and mid-market"},
        ethics={"credibility_score": 6, "credibility_label": "Mixed",
                "recommendation": "Get certifications"},
        psychology={"why_it_worked": "Identity signaling", 
                    "primary_trigger": "Identity signaling",
                    "what_customers_felt": "Pride", "sentiment_score": 8,
                    "key_lesson": "Authenticity matters"},
        influencers={"shortlist": [{"name": "Sample Creator", "region": "India",
                                     "platform": "Instagram", "fit_score": 8,
                                     "why_they_fit": "Strong audience overlap",
                                     "collaboration_format": "Sponsored post"}]},
        synthesis={"executive_summary": "Test summary", 
                  "top_opportunity": "Test opportunity",
                  "cross_agent_insight": "Test insight", 
                  "risk_flag": "Test risk",
                  "recommended_actions": ["Action 1", "Action 2"]},
        critic={"score": 9},
        content={"instagram_captions": [{"tone": "Bold", "caption": "Test caption",
                                          "hashtags": "#test"}],
                "email_subject": "Test subject",
                "ad_headlines": ["Test headline"],
                "brand_story": "Test story"}
    )
    
    print(sample_report)
    print("\n✓ Report Agent working correctly")